### ISSUE TITLE
Can Multiple Containers Share One bg-sync service/mount point?

### ISSUE THREAD

**Issue by henrymazza** [cweagans/docker-bg-sync#29]
I assumed it could, but it only syncs to the first service specified in the `volumes_from` list. Plus: my containers won't share the same mount: with `docker inspect` shows that each one has a distinct mount point. Is it an intrinsic limitation or am I missing something in the configs? 

```yaml
services:
  web:
    working_dir: /app-sync
    volumes:
      - /app-sync

  spring:
    working_dir: /app-sync
    volumes:
      - /app-sync

  sidekiq:
    working_dir: /app-sync
    volumes:
      - /app-sync

  bg-sync:
    image: cweagans/bg-sync
    volumes:
      - .:/source
    volumes_from:
      - spring
      - web
      - sidekiq
    environment:
      - SYNC_DESTINATION=/app-sync
      - SYNC_MAX_INOTIFY_WATCHES=40000
      - SYNC_VERBOSE=1
    privileged: true

```
