### ISSUE TITLE
Warning: No archive files were found for these roots, whose canonical names are

### ISSUE THREAD

**Issue by mschop** [cweagans/docker-bg-sync#30]
Hi,

this is my docker-composer service:

```
  files_syncer:
    build:
      context: services/files_syncer
      args:
        - USER_ID=${USER_ID}
    volumes:
      - "./:/source:cached"
      - "code:/code"
      - "files_syncer_root:/root"
    environment:
      - SYNC_DESTINATION=/code
      - UNISON_USER=app
      - UNISON_UID=${USER_ID}
      - UNISON_GROUP=app
      - UNISON_GID=${USER_ID}
      - SYNC_MAX_INOTIFY_WATCHES=250000
      - SYNC_PREFER=newer
      - SYNC_VERBOSE=1
    privileged: true
```

I don't understand, why I get the following message:

```
Warning: No archive files were found for these roots, whose canonical names are:
	/source
	/code
This can happen either
because this is the first time you have synchronized these roots, 
or because you have upgraded Unison to a new version with a different
archive format.
```

I let the complete process run (successfully) and stop the watcher.
When I start it again, the message is shown again.
I would have expected, that this message does not show up again.
