### ISSUE TITLE
Exclusions

### ISSUE THREAD

**Issue by Harrisonbro** [cweagans/docker-bg-sync#4]
Is there a way to exclude certain files or folders from being synced? I'm thinking specifically of my `.git` directory which doesn't need to be synced into the container.

**Comment by wvteijlingen** [comment]
FYI, you can use the `SYNC_EXTRA_UNISON_PROFILE_OPTS` environment variable for this. For example:

```yaml
bg-sync:
    image: cweagans/bg-sync
    volumes:
      - .:/source
    volumes_from:
      - web
    environment:
      SYNC_EXTRA_UNISON_PROFILE_OPTS: |
        ignore = Path tmp/*
        ignore = Path .ebextensions/*
        ignore = Path .elasticbeanstalk/*
```
