### ISSUE TITLE
Not Syncing

### ISSUE THREAD

**Issue by FatherShawn** [cweagans/docker-bg-sync#7]
I have your container running via docker-compose without detaching docker-compose so I can watch the logs.  If I change a file on my Mac and then inspect `/source` by executing a shell in your container, I can see the file changed in source, but there is no reaction in the log and the change does not propogate to destination.  Here's the compose section:

```
  bg-sync:
    image: cweagans/bg-sync
    networks:
      - internal
    volumes:
      - .:/source
      - docroot:/var/www
    privileged: true
    environment:
      SYNC_VERBOSE: 1
      SYNC_DESTINATION: /var/www
      SYNC_MAX_INOTIFY_WATCHES: 40000
      SYNC_NODELETE_SOURCE: 0
      SYNC_EXTRA_UNISON_PROFILE_OPTS: |
       ignore = Name {node_modules,bower_components,.DS_Store}
       ignore = Path docroot/sites/default/files
volumes:
  docroot:
```

Any recommendation on how to debug?
